### ISSUE TITLE
Infografía-de-hilos

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/infografia-de-hilos-Brisa-4#2]
[Infografía de hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Brisa-4/files/6528953/Infografia.de.hilos.pdf)

**Comment by MariaC232** [comment]
Buen trabajo.
Calificación: 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado
